/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
@Test
public void testAppReternHelloWorld() {
App classUnderTest = new App();
assertEquals("Hello World", classUnderTest.getGreeting());
/*“Hello World!”->“Hello World”に変更*/
}
}
